= Лабораторна робота №3

*Тема:* Основи роботи з компонентами.
Шаблони.
Директиви.

*Мета:* опанувати базові принципи створення та використання компонентів у Vue.js.
Ознайомитися з шаблонами в компонентах Vue.
Навчитися використовувати основні директиви Vue.js у шаблонах.

== Самостйна робота:

. https://ua.vuejs.org/guide/introduction.html
. https://ua.vuejs.org/guide/essentials/template-syntax.html
. https://ua.vuejs.org/guide/essentials/reactivity-fundamentals.html
. https://ua.vuejs.org/guide/essentials/class-and-style.html
. https://ua.vuejs.org/guide/essentials/conditional.html
. https://ua.vuejs.org/guide/essentials/list.html
. https://ua.vuejs.org/guide/essentials/component-basics.html
. https://ua.vuejs.org/guide/extras/composition-api-faq.html

== Вимоги до звіту:

. Дана лабораторна робота виконується в окремому репозиторії
. Дотримання TypeScript-типізації
. Під час написання застосунку, дотримуватись style guide - https://ua.vuejs.org/style-guide/
. Дотримання https://www.conventionalcommits.org/[Conventional commits specification] відповідно до кожного завдання
. Код повинен бути розміщений в особистому GitHub репозиторії студента

== Практична частина

. Пройдіть весь tutorial https://ua.vuejs.org/tutorial/#step-1 (Стиль API: Композиційний, SFC).
Результат виконання кожного задання фіксувати у вигляді скріншоту з відповідним неймінгом (step-1.(jpg|png)).

. Створіть новий проєкт Vue 3 за допомогою vue-create.
** Виокристовуйте TypeScript з Композиційним API (Add TypeScript?
Yes).
Що таке Композиційний API: https://ua.vuejs.org/guide/extras/composition-api-faq.html
** Використовуйте Eslint (Add ESLint for code quality?
Yes).
** Ознайомтесь зі структурою стартового проєкту.
** Під час написання застосунку, дотримуватись style guide - https://ua.vuejs.org/style-guide/

. Створіть простий компонент Users.vue та імпортуйте його в App.vue, який буде мати наступну структуру:
** Шаблон з інформацією про користувача на основі даних представлених у файлі user.json.
Для цього використовуйте поля gender, name, location, email, phone, picture, dob.
** Виведіть дані про користувача на ui.
** Додайте стилі для картки користувача.

. У шаблоні компонента юзера додайте:
** Використання директиви v-if, щоб показувати вік тільки якщо він більше 18 років.
** До об'єкту юзера додайте поле hobbies - це має бути масив зі списком хоббі юзера.
З використанням директиви v-for відобразити список хобі користувача.
** Реалізуйте прив'язку стилів для умовного фарбування картки в залежності від віку користувача (до 18 — minor, 18–30 — young, 31–50 — adult, понад 50 — senior).
Кольори на вподобання студента.
Використати об'єктний синтаксис :class.
** До об'єкту юзера додайте поле details - довільна коротка інформація про юзера.
Показати/приховати додаткову інформацію про користувача details (використати директиву v-show).

. У шаблоні компонента Users.vue реалізуйте список юзерів:
** Розширить список юзерів до 10 включно та виведіть на ui весь список юзерів.
** Додайте фотографії користувачів до проєкту.
Розмістіть зображення в директорії public/users.
Для кожного користувача в об'єкті (поле picture) вкажіть шлях до відповідної фотографії.
Виведіть фотографію користувача за допомогою прив'язки атрибута src директивою v-bind.
Значення атрибута alt сформуйте динамічно на основі імені та прізвища користувача.
** Додати перевірку, якщо список пустий, вивести напис - 'Список юзерів пустий'.
** Додайте над списком юзерів toolbar з фільтром у вигляді кнопок ([ Всі ] [ Чоловіки ] [ Жінки ]).
По кліку на відповідно кнопку, скривати юзерів в залежності від статі.
** Додайте можливість фільтрації юзерів за віком 18+ вигляді кнопок ([ Всі ] [ 18 + ]).
По кліку на відповідно кнопку, скривати юзерів в залежності від віку.
** Додайте можливість сортування списку юзерів у вигляді кнопок ([ Ім'я ↑ ] [ Ім'я ↓ ] [ Вік ↑ ] [ Вік ↓ ]).
При цьому сортування повинно не ламати фільтрацію юзерів.
** Додайте можливість скинути всі фільтри та сортування до дефолтного стану у вигляді кнопки ([ Очистити все ]).

. Скріншоти завдання 1 помістіть у ваш проєкт у директорію public/tutorial.

== Контрольні питання

. Що таке компонент у Vue.js та яку роль він виконує в структурі застосунку?
. Що таке Single File Component (SFC) у Vue.js?
Які основні секції може містити SFC?
. Що таке шаблон (template) компонента Vue та які конструкції можна використовувати в ньому?
. У чому полягає різниця між звичайним HTML та шаблоном Vue?
. Що таке директиви Vue.js?
Який синтаксис використовується для їх запису?
. Для чого використовується директива v-bind?
Наведіть приклад її використання.
. Яка різниця між v-bind:src="..." та :src="..."?
. Для чого використовується директива v-if?
Як вона впливає на DOM?
У чому різниця між v-if, v-else-if та v-else?
У чому відмінність між директивами v-if та v-show?
. Для чого використовується директива v-for?
Як правильно використовувати :key разом із v-for?
. Що таке реактивність у Vue та як вона пов'язана зі зміною даних у шаблоні?

